<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $softwareCategory = Category::where('slug', 'software-licenses')->first();
        $hardwareCategory = Category::where('slug', 'computer-hardware')->first();
        $ebookCategory = Category::where('slug', 'ebooks-courses')->first();
        $networkingCategory = Category::where('slug', 'networking-equipment')->first();
        $accessoriesCategory = Category::where('slug', 'accessories-peripherals')->first();

        $products = [
            // Digital Products
            [
                'category_id' => $softwareCategory->id,
                'name' => 'Windows 11 Pro License',
                'slug' => 'windows-11-pro',
                'description' => 'Official Windows 11 Pro single-user license with activation support and 1 year technical support',
                'price' => 199.99,
                'type' => 'digital',
                'sku' => 'WIN11PRO-001',
                'stock' => null,
                'image_url' => 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400&h=400&fit=crop',
            ],
            [
                'category_id' => $softwareCategory->id,
                'name' => 'Microsoft Office 365 Annual',
                'slug' => 'office-365-annual',
                'description' => 'Annual subscription to Microsoft Office 365 with cloud storage and updates',
                'price' => 99.99,
                'type' => 'digital',
                'sku' => 'OFFICE365-001',
                'stock' => null,
                'image_url' => 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=400&h=400&fit=crop',
            ],
            [
                'category_id' => $ebookCategory->id,
                'name' => 'Advanced PHP Development Course',
                'slug' => 'php-dev-course',
                'description' => 'Comprehensive online course covering advanced PHP, design patterns, and best practices',
                'price' => 79.99,
                'type' => 'digital',
                'sku' => 'COURSE-PHP-001',
                'stock' => null,
                'image_url' => 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400&h=400&fit=crop',
            ],
            [
                'category_id' => $ebookCategory->id,
                'name' => 'Clean Code E-Book Bundle',
                'slug' => 'clean-code-bundle',
                'description' => '5 essential e-books on code quality, design patterns, and software architecture',
                'price' => 49.99,
                'type' => 'digital',
                'sku' => 'EBOOK-BUNDLE-001',
                'stock' => null,
                'image_url' => 'https://m.media-amazon.com/images/I/71T7aD3EOTL._UF1000,1000_QL80_.jpg',
            ],

            // Physical Products
            [
                'category_id' => $hardwareCategory->id,
                'name' => 'NVIDIA RTX 4090 Graphics Card',
                'slug' => 'nvidia-rtx-4090',
                'description' => '24GB GDDR6X memory, PCIe 4.0, suitable for gaming and professional workloads',
                'price' => 1599.99,
                'type' => 'physical',
                'sku' => 'GPU-RTX4090-001',
                'stock' => 5,
                'image_url' => 'https://cdn-ultra.esempla.com/storage/webp/ebc7fcf2-df28-442f-ac61-48d5a2e53232.webp',
            ],
            [
                'category_id' => $hardwareCategory->id,
                'name' => 'Intel Core i9-13900K Processor',
                'slug' => 'intel-core-i9-13900k',
                'description' => '24-core processor with 8P+16E cores, 32 threads, 5.8GHz boost clock',
                'price' => 589.99,
                'type' => 'physical',
                'sku' => 'CPU-I9-13900K-001',
                'stock' => 8,
                'image_url' => 'https://www.custompc.com/wp-content/sites/custompc/2023/02/intel-core-i9-13900K-review-01.jpg',
            ],
            [
                'category_id' => $hardwareCategory->id,
                'name' => 'Samsung 990 Pro NVMe SSD 4TB',
                'slug' => 'samsung-990-pro-4tb',
                'description' => 'PCIe 4.0 NVMe SSD with up to 7,100 MB/s read speed, includes heatsink',
                'price' => 449.99,
                'type' => 'physical',
                'sku' => 'SSD-990PRO-4TB-001',
                'stock' => 12,
                'image_url' => 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=400&h=400&fit=crop',
            ],
            [
                'category_id' => $networkingCategory->id,
                'name' => 'Netgear Nighthawk Pro WiFi 6 Router',
                'slug' => 'netgear-nighthawk-wifi6',
                'description' => 'WiFi 6 (802.11ax) router with 32 stream technology and 12-stream AXE7800',
                'price' => 299.99,
                'type' => 'physical',
                'sku' => 'ROUTER-NIGHTHAWK-001',
                'stock' => 6,
                'image_url' => 'https://m.media-amazon.com/images/I/51M0N5o16-L.jpg',
            ],
            [
                'category_id' => $networkingCategory->id,
                'name' => 'Cat8 Ethernet Cable 100ft',
                'slug' => 'cat8-ethernet-100ft',
                'description' => 'Heavy-duty Cat8 ethernet cable certified for 40Gbps speeds, with shielding',
                'price' => 29.99,
                'type' => 'physical',
                'sku' => 'CABLE-CAT8-100FT-001',
                'stock' => 25,
                'image_url' => 'https://i5.walmartimages.com/seo/Cat-8-Ethernet-Cable-100ft-Outdoor-Indoor-Heavy-Duty-High-Speed-Cat-8-LAN-Network-Cable-40Gbps-2000MHz-Gold-Plated-RJ45-Connector-Weatherproof-S-FTP_49309b42-ec1e-4596-a124-c95f7e6bd9b2.5b7f6e3dd60feaa699746a702e4ce8b9.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF',
            ],
            [
                'category_id' => $hardwareCategory->id,
                'name' => 'Corsair Dominator DDR5 32GB (2x16GB)',
                'slug' => 'corsair-dominator-ddr5-32gb',
                'description' => 'DDR5 high-performance RAM with XMP 3.0 profiles, 6000MHz',
                'price' => 179.99,
                'type' => 'physical',
                'sku' => 'RAM-DDR5-32GB-001',
                'stock' => 15,
                'image_url' => 'https://m.media-amazon.com/images/I/61OyBIH+eEL.jpg',
            ],
            [
            'category_id' => $softwareCategory->id,
            'name' => 'Adobe Creative Cloud All Apps',
            'slug' => 'adobe-creative-cloud-all-apps',
            'description' => 'Full Adobe Creative Cloud suite including Photoshop, Illustrator, Premiere Pro, and After Effects',
            'price' => 239.99,
            'type' => 'digital',
            'sku' => 'ADOBE-CC-001',
            'stock' => null,
            'image_url' => 'https://images.unsplash.com/photo-1545239351-1141bd82e8a6?w=400&h=400&fit=crop',
        ],
        [
            'category_id' => $softwareCategory->id,
            'name' => 'JetBrains IntelliJ IDEA Ultimate',
            'slug' => 'intellij-idea-ultimate',
            'description' => 'Professional IDE for Java, Kotlin, PHP, Python, and modern web development',
            'price' => 149.99,
            'type' => 'digital',
            'sku' => 'JETBRAINS-IDEA-001',
            'stock' => null,
            'image_url' => 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=400&h=400&fit=crop',
        ],
        [
            'category_id' => $softwareCategory->id,
            'name' => 'VPN Premium Annual Subscription',
            'slug' => 'vpn-premium-annual',
            'description' => 'Secure VPN service with unlimited bandwidth, global servers, and encrypted browsing',
            'price' => 69.99,
            'type' => 'digital',
            'sku' => 'VPN-PREMIUM-001',
            'stock' => null,
            'image_url' => 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=400&h=400&fit=crop',
        ],
        [
            'category_id' => $ebookCategory->id,
            'name' => 'Laravel Mastery Video Course',
            'slug' => 'laravel-mastery-course',
            'description' => 'Advanced Laravel development course covering APIs, queues, testing, and deployment',
            'price' => 89.99,
            'type' => 'digital',
            'sku' => 'COURSE-LARAVEL-001',
            'stock' => null,
            'image_url' => 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=400&h=400&fit=crop',
        ],
        [
            'category_id' => $ebookCategory->id,
            'name' => 'Cybersecurity Fundamentals E-Book',
            'slug' => 'cybersecurity-fundamentals-ebook',
            'description' => 'Comprehensive beginner to intermediate guide on cybersecurity principles and practices',
            'price' => 39.99,
            'type' => 'digital',
            'sku' => 'EBOOK-CYBERSEC-001',
            'stock' => null,
            'image_url' => 'https://images.unsplash.com/photo-1510511459019-5dda7724fd87?w=400&h=400&fit=crop',
        ],

        [
            'category_id' => $hardwareCategory->id,
            'name' => 'Logitech MX Master 3S Wireless Mouse',
            'slug' => 'logitech-mx-master-3s',
            'description' => 'Ergonomic wireless productivity mouse with ultra-fast scrolling and silent clicks',
            'price' => 119.99,
            'type' => 'physical',
            'sku' => 'MOUSE-MX3S-001',
            'stock' => 20,
            'image_url' => 'https://images.unsplash.com/photo-1527814050087-3793815479db?w=400&h=400&fit=crop',
        ],
        [
            'category_id' => $hardwareCategory->id,
            'name' => 'Keychron K8 Mechanical Keyboard',
            'slug' => 'keychron-k8-keyboard',
            'description' => 'Wireless mechanical keyboard with RGB backlighting and hot-swappable switches',
            'price' => 99.99,
            'type' => 'physical',
            'sku' => 'KEYBOARD-K8-001',
            'stock' => 18,
            'image_url' => 'https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?w=400&h=400&fit=crop',
        ],
        [
            'category_id' => $hardwareCategory->id,
            'name' => 'LG UltraGear 34-inch Curved Monitor',
            'slug' => 'lg-ultragear-34-monitor',
            'description' => '34-inch ultrawide gaming monitor with 144Hz refresh rate and HDR support',
            'price' => 799.99,
            'type' => 'physical',
            'sku' => 'MONITOR-LG34-001',
            'stock' => 7,
            'image_url' => 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400&h=400&fit=crop',
        ],
        [
            'category_id' => $networkingCategory->id,
            'name' => 'TP-Link 24-Port Gigabit Switch',
            'slug' => 'tplink-24port-switch',
            'description' => 'Managed 24-port gigabit ethernet switch with VLAN and QoS support',
            'price' => 219.99,
            'type' => 'physical',
            'sku' => 'SWITCH-24PORT-001',
            'stock' => 10,
            'image_url' => 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400&h=400&fit=crop',
        ],
        [
            'category_id' => $hardwareCategory->id,
            'name' => 'Sony WH-1000XM5 Wireless Headphones',
            'slug' => 'sony-wh1000xm5',
            'description' => 'Premium noise-canceling wireless headphones with 30-hour battery life',
            'price' => 399.99,
            'type' => 'physical',
            'sku' => 'HEADPHONES-SONY-001',
            'stock' => 14,
            'image_url' => 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop',
        ],
[
    'category_id' => $softwareCategory->id,
    'name' => 'Bitdefender Total Security',
    'slug' => 'bitdefender-total-security',
    'description' => 'Advanced antivirus and cybersecurity suite for multiple devices',
    'price' => 59.99,
    'type' => 'digital',
    'sku' => 'BITDEFENDER-001',
    'stock' => null,
    'image_url' => 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=400&h=400&fit=crop',
],
[
    'category_id' => $softwareCategory->id,
    'name' => 'Autodesk AutoCAD 2025',
    'slug' => 'autodesk-autocad-2025',
    'description' => 'Industry-standard CAD software for architecture and engineering design',
    'price' => 349.99,
    'type' => 'digital',
    'sku' => 'AUTOCAD-2025-001',
    'stock' => null,
    'image_url' => 'https://images.unsplash.com/photo-1504639725590-34d0984388bd?w=400&h=400&fit=crop',
],
[
    'category_id' => $softwareCategory->id,
    'name' => 'NordVPN 2-Year Plan',
    'slug' => 'nordvpn-2year-plan',
    'description' => 'Secure encrypted VPN with worldwide servers and malware protection',
    'price' => 89.99,
    'type' => 'digital',
    'sku' => 'NORDVPN-001',
    'stock' => null,
    'image_url' => 'https://images.unsplash.com/photo-1510511459019-5dda7724fd87?w=400&h=400&fit=crop',
],
[
    'category_id' => $ebookCategory->id,
    'name' => 'Laravel Mastery Complete Course',
    'slug' => 'laravel-mastery-complete-course',
    'description' => 'Deep dive into Laravel APIs, queues, testing, authentication, and deployment',
    'price' => 89.99,
    'type' => 'digital',
    'sku' => 'COURSE-LARAVEL-002',
    'stock' => null,
    'image_url' => 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=400&h=400&fit=crop',
],
[
    'category_id' => $ebookCategory->id,
    'name' => 'Docker & Kubernetes Handbook',
    'slug' => 'docker-kubernetes-handbook',
    'description' => 'Comprehensive guide to containerization and orchestration technologies',
    'price' => 44.99,
    'type' => 'digital',
    'sku' => 'EBOOK-DOCKER-001',
    'stock' => null,
    'image_url' => 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400&h=400&fit=crop',
],
[
    'category_id' => $ebookCategory->id,
    'name' => 'Cybersecurity Fundamentals',
    'slug' => 'cybersecurity-fundamentals',
    'description' => 'Practical guide to modern cybersecurity threats and defense techniques',
    'price' => 39.99,
    'type' => 'digital',
    'sku' => 'EBOOK-CYBER-001',
    'stock' => null,
    'image_url' => 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=400&h=400&fit=crop',
],
[
    'category_id' => $ebookCategory->id,
    'name' => 'Modern JavaScript Architecture',
    'slug' => 'modern-javascript-architecture',
    'description' => 'Learn scalable frontend architecture using modern JavaScript frameworks',
    'price' => 34.99,
    'type' => 'digital',
    'sku' => 'EBOOK-JS-001',
    'stock' => null,
    'image_url' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=400&h=400&fit=crop',
],
[
    'category_id' => $ebookCategory->id,
    'name' => 'AI & Machine Learning Essentials',
    'slug' => 'ai-machine-learning-essentials',
    'description' => 'Beginner-friendly guide to AI concepts, neural networks, and machine learning',
    'price' => 54.99,
    'type' => 'digital',
    'sku' => 'EBOOK-AI-001',
    'stock' => null,
    'image_url' => 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=400&h=400&fit=crop',
],
[
    'category_id' => $hardwareCategory->id,
    'name' => 'Elgato Stream Deck XL',
    'slug' => 'elgato-stream-deck-xl',
    'description' => 'Advanced customizable control pad for streamers and productivity workflows',
    'price' => 249.99,
    'type' => 'physical',
    'sku' => 'STREAMDECK-XL-001',
    'stock' => 9,
    'image_url' => 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=400&h=400&fit=crop',
],
[
    'category_id' => $networkingCategory->id,
    'name' => 'Ubiquiti UniFi 6 Access Point',
    'slug' => 'ubiquiti-unifi-6-ap',
    'description' => 'Enterprise-grade WiFi 6 access point with seamless roaming support',
    'price' => 179.99,
    'type' => 'physical',
    'sku' => 'UNIFI6-AP-001',
    'stock' => 11,
    'image_url' => 'https://images.unsplash.com/photo-1647427060118-4911c9821b82?w=400&h=400&fit=crop',
],
[
    'category_id' => $networkingCategory->id,
    'name' => 'ASUS ROG Rapture Gaming Router',
    'slug' => 'asus-rog-rapture-router',
    'description' => 'Tri-band gaming router optimized for low latency and high-speed performance',
    'price' => 429.99,
    'type' => 'physical',
    'sku' => 'ROG-ROUTER-001',
    'stock' => 6,
    'image_url' => 'https://images.unsplash.com/photo-1606904825846-647eb07f5be2?w=400&h=400&fit=crop',
],
[
    'category_id' => $networkingCategory->id,
    'name' => 'Cisco Small Business Firewall',
    'slug' => 'cisco-small-business-firewall',
    'description' => 'Hardware firewall appliance with VPN and advanced threat protection',
    'price' => 349.99,
    'type' => 'physical',
    'sku' => 'CISCO-FW-001',
    'stock' => 4,
    'image_url' => 'https://images.unsplash.com/photo-1563770660941-20978e870e26?w=400&h=400&fit=crop',
],
[
    'category_id' => $networkingCategory->id,
    'name' => 'Mesh WiFi 6 System 3-Pack',
    'slug' => 'mesh-wifi-6-system',
    'description' => 'Whole-home mesh networking system with seamless WiFi 6 coverage',
    'price' => 329.99,
    'type' => 'physical',
    'sku' => 'MESH-WIFI6-001',
    'stock' => 8,
    'image_url' => 'https://images.unsplash.com/photo-1573164713714-d95e436ab8d6?w=400&h=400&fit=crop',
],
[
    'category_id' => $accessoriesCategory->id,
    'name' => 'Anker 737 Power Bank 24000mAh',
    'slug' => 'anker-737-power-bank',
    'description' => 'High-capacity portable charger with fast charging support for laptops and phones',
    'price' => 149.99,
    'type' => 'physical',
    'sku' => 'ANKER-737-001',
    'stock' => 25,
    'image_url' => 'https://cdn.shopify.com/s/files/1/0493/9834/9974/products/A1289011-Anker_737_Power_Bank_PowerCore_24K_1.png?v=1775967275',
],
[
    'category_id' => $accessoriesCategory->id,
    'name' => 'Belkin USB-C Docking Station',
    'slug' => 'belkin-usbc-docking-station',
    'description' => 'Multi-port USB-C docking station with HDMI, Ethernet, and USB 3.0 support',
    'price' => 189.99,
    'type' => 'physical',
    'sku' => 'DOCK-BELKIN-001',
    'stock' => 13,
    'image_url' => 'https://images.unsplash.com/photo-1580894908361-967195033215?w=400&h=400&fit=crop',
],
[
    'category_id' => $accessoriesCategory->id,
    'name' => 'Razer Firefly RGB Mouse Pad',
    'slug' => 'razer-firefly-rgb-mousepad',
    'description' => 'Hard surface gaming mouse pad with customizable RGB lighting',
    'price' => 59.99,
    'type' => 'physical',
    'sku' => 'RAZER-FIREFLY-001',
    'stock' => 18,
    'image_url' => 'https://cdn-ultra.esempla.com/storage/7f2cf64a-b3dc-4cba-8181-6f7696c30dc5.png',
],
[
    'category_id' => $accessoriesCategory->id,
    'name' => 'Samsung T7 Portable SSD 2TB',
    'slug' => 'samsung-t7-portable-ssd',
    'description' => 'Portable USB-C SSD with ultra-fast transfer speeds and compact design',
    'price' => 179.99,
    'type' => 'physical',
    'sku' => 'SAMSUNG-T7-001',
    'stock' => 17,
    'image_url' => 'https://cdn-ultra.esempla.com/storage/webp/3e8ea604-4cf8-443b-8fae-9f2a8dbc020f.webp',
],
[
    'category_id' => $accessoriesCategory->id,
    'name' => 'Blue Yeti USB Microphone',
    'slug' => 'blue-yeti-usb-microphone',
    'description' => 'Professional USB microphone ideal for streaming, podcasts, and recording',
    'price' => 129.99,
    'type' => 'physical',
    'sku' => 'BLUE-YETI-001',
    'stock' => 14,
    'image_url' => 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=400&h=400&fit=crop',
],
        ];

        foreach ($products as $product) {
            Product::updateOrCreate(['sku' => $product['sku']], $product);
        }
    }
}
